### PR TITLE
align columns

### PR DESCRIPTION
**Pull request by dmd**
use column in _goto_list_aliases
fix column in _goto_list_aliases to actually work

### CODE REVIEW

**Comment by dmd** [comment]
Note that SC2005 is incorrect, as column behaves differently w/ stderr.  Unless you can figure out a different way to make this work...

**Comment by iridakos** [comment]
Any objection with [this commit](https://github.com/iridakos/goto/pull/26/commits/28c98d48df0d59fe707d23f54e9fcb6ccb1eb63e)?

**Comment by iridakos** [comment]
If I understand correctly, this [commit](https://github.com/iridakos/goto/pull/26/commits/28c98d48df0d59fe707d23f54e9fcb6ccb1eb63e) breaks ksh? If yes, why?

**Comment by iridakos** [comment]
Super! Thanks for the contribution!!!

**Pull request merged**
