### PR TITLE
Ask for sudo password if needed

### PR DESCRIPTION
**Pull request by JBlond**
Ask for sudo password if needed
Take two

### CODE REVIEW

**Comment by JBlond** [comment]
Folllow up for PR #47

**Comment by JBlond** [comment]
@iridakos Can you please take a look at this?

**Comment by iridakos** [comment]
@JBlond Hi, I will have to check it first and I will merge it if it's working.

Thank you for the contribution :+1:

**Comment by JBlond** [comment]
@iridakos I don't want to be pushy, but it has been a while.

**Comment by iridakos** [comment]
Hi @JBlond,

I've been very busy lately. Sorry for taking too long to review this. I merged another pull request in the past without checking if it works because the changes seemed fine but it broke the script. I don't want this to happen again that's why I need to check your pull request as well.

Have you checked it?

**Comment by iridakos** [comment]
I just checked the changes.

I don't want to enforce the execution of the `sudo` command explicitly in the script. There are [systems that don't have the package installed](https://unix.stackexchange.com/questions/354928/bash-sudo-command-not-found) by default.

Thank you for the contribution.

**Pull request closed without merging**
