### PR TITLE
added ability to use hyphen and underscore in aliases

### PR DESCRIPTION
**Pull request by jcavejr**
Ex:
`goto -r test_alias ~`

### CODE REVIEW

**Comment by iridakos** [comment]
Excellent :+1:

I will check the functionality manually (till #2 is resolved) and I will merge it asap.

Thank you very much for the contribution.

**Comment by iridakos** [comment]
When user types the following:
```bash
goto -<tab>
```
we show the list of the available commands. I don't want this functionality to go away.

Can you update your changes so that an alias can't start with a dash(-)?

Thanks!

**Comment by jcavejr** [comment]
Should be good to go now!

**Comment by iridakos** [comment]
Thanks, I fill fix an issue on it (it doesn't allow this `a4-rec`) and I will merge it.

**Pull request merged**
